spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://182.92.71.18:3306/me_warehouse?useUnicode=true&characterEncoding=utf8&useSSL=true
#    username: ME_Warehouse
#    password: hcWFjG8kzZrJ65ny
    url: jdbc:mysql://127.0.0.1:3306/me_warehouse_back?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initial-size: 10
      # 连接池中最小连接数量
      min-idle: 10
      # 连接池用最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒。
      max-wait: 60000
      # 关闭空闲连接的检测时间间隔 Destroy 线程会检测连接的间隔时间，如果连接空闲时间大于等于则关闭物理连接。
      time-between-eviction-runs-millis: 60000
      # 连接的最小生存时间，连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 验证数据库服务可用性的 sql，用来检测连接是否有效的 sql。oracle 应该写成 SELECT 1 FROM DUAL
      validation-query: SELECT 1
      # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效，建议配置为 true，不影响性能，并且保证安全性。
      test-while-idle: true
      # 申请连接时直接检测连接是否有效，申请连接时执行 validationQuery 检测连接是否有效，开启会降低性能。
      test-on-borrow: true
      # 归还连接时检测连接是否有效，归还连接时执行 validationQuery 检测连接是否有效，开启会降低性能。
      test-on-return: true
      # 开启 PSCache
      pool-prepared-statements: true
      # 设置 PSCache 的值
      max-pool-prepared-statement-per-connection-size: 20
      # 连接出错后再尝试连接三次
      connection-error-retry-attempts: 3
      # 数据库服务宕机自动重连机制
      break-after-acquire-failure: true
      # 连接出错后重试时间间隔
      time-between-connect-error-millis: 300000
      # 异步初始化策略
      async-init: true
      # 是否自动回收超时连接
      remove-abandoned: true
      # 超时时间(秒)
      remove-abandoned-timeout: 1800
      # 事务超时时间
      transaction-query-timeout: 6000
      # 配置监控统计拦截的 filters，去掉后监控界面 sql 无法统计，wall 用于防火墙
      filters: stat,wall,log4j2
      #      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      #      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        enable_lazy_load_no_trans: true
    show-sql: true
    open-in-view: true

  devtools:
    add-properties: false
  mvc:
    log-request-details: true
  codec:
    log-request-details: true

me:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5[freeter]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
logging:
  config: classpath:logback-spring.xml
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package:
